FROM java:8-jdk
MAINTAINER Manuel Gómez <mgomez@mahisoft.com>

RUN mkdir -p /opt/mamute
WORKDIR /opt/mamute

COPY artifacts/mamute-1.5.0.war mamute.war
RUN unzip mamute.war

EXPOSE 80

COPY setup.sh ./
RUN chmod +x setup.sh

CMD ["./setup.sh"]
